### ISSUE TITLE
CC65 benchmarks do not use "-Cl" (static locals) optimization

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [KarolS/millfork-benchmarks#3]
It seems that CC65 was tested in a very unoptimal way (no static local optimization).
CC65 both C standard constructs (register) and pragmas to use zero page. 

I have played with the sieve in CC65 in:
https://github.com/Fabrizio-Caruso/Sieve

**Comment by KarolS** [comment]
There is 

```c
#pragma static-locals(1);
```

in [`benchcommon.h`](https://github.com/KarolS/millfork-benchmarks/blob/master/6502/benchcommon.h).

The only hot variables (`S` and `I`) are already defined as `register` and they do land in the zero page. `S` is contained in `regbank+4` and `regbank+5`, and `I` is contained in `regbank+3`.

**Comment by Fabrizio-Caruso** [comment]
Sorry, you are right.
